modLoader = "javafml"
loaderVersion = "[49,)"
#issueTrackerURL = ""
license = "Mozilla Public License Version 2.0"

[[mods]]
modId = "cavedust"
version = "${version}"
displayName = "Cave Dust"
authors = "LizCannotEven"
description = '''
This mod adds cave dust to caves!
'''
#logoFile = ""

[[dependencies.cavedust]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cavedust]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cavedust]]
modId = "architectury"
mandatory = true
versionRange = "[11,)"
ordering = "NONE"
side = "BOTH"
